# Generated by Django 2.2.1 on 2019-05-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_ringi_seq', models.CharField(max_length=20)),
                ('title_name', models.CharField(max_length=100)),
                ('character_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('bne_pic', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
