# Generated by Django 2.2.3 on 2019-07-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipdds_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dao',
        ),
        migrations.DeleteModel(
            name='Proposal02',
        ),
    ]
